export const SKILL_CATEGORIES = [
  {
    id: 'frontend',
    label: 'Front-end',
    icon: '◐',
    accent: '#60a5fa',
    accentSoft: 'rgba(96, 165, 250, 0.18)',
    score: 86,
    summary: 'Interfaces modernas, responsivas e com forte cuidado em UX.',
    skills: [
      { name: 'React', level: 88, note: 'Hooks, RSC, performance' },
      { name: 'TypeScript', level: 90, note: 'Tipagem estrita em produção' },
      { name: 'CSS Moderno', level: 85, note: 'Grid, container queries, layers' },
      { name: 'Design Responsivo', level: 90, note: 'Mobile-first sempre' },
      { name: 'Estado / Data Fetch', level: 82, note: 'React Query, Zustand' },
    ],
  },
  {
    id: 'backend',
    label: 'Back-end',
    icon: '◑',
    accent: '#a78bfa',
    accentSoft: 'rgba(167, 139, 250, 0.18)',
    score: 92,
    summary: 'APIs robustas, design de domínio e segurança first-class.',
    skills: [
      { name: 'Node.js / Express', level: 92, note: 'Serviços em produção' },
      { name: 'Python / FastAPI', level: 88, note: 'APIs async, pydantic' },
      { name: 'Design de API REST', level: 95, note: 'Contratos limpos' },
      { name: 'PostgreSQL', level: 92, note: 'Modelagem e indices' },
      { name: 'Auth & Segurança', level: 85, note: 'JWT, OAuth, RBAC' },
    ],
  },
  {
    id: 'data',
    label: 'Data',
    icon: '◓',
    accent: '#34d399',
    accentSoft: 'rgba(52, 211, 153, 0.18)',
    score: 90,
    summary: 'Pipelines ETL, modelagem dimensional e analytics confiável.',
    skills: [
      { name: 'Pipelines ETL', level: 90, note: 'Airflow, ADF' },
      { name: 'Modelagem de Dados', level: 88, note: 'Star schema, dbt' },
      { name: 'Power BI', level: 87, note: 'Dashboards estratégicos' },
      { name: 'SQL Avançado', level: 92, note: 'Window, CTEs, perf' },
      { name: 'Data Lake', level: 80, note: 'Azure, layered arch' },
    ],
  },
  {
    id: 'ai',
    label: 'AI',
    icon: '◔',
    accent: '#f472b6',
    accentSoft: 'rgba(244, 114, 182, 0.18)',
    score: 84,
    summary: 'Integrações com LLMs, agentes e produtos assistidos por IA.',
    skills: [
      { name: 'Integrações LLM', level: 86, note: 'OpenAI, Anthropic' },
      { name: 'Agentes de IA', level: 80, note: 'Tool use, planners' },
      { name: 'Prompt Engineering', level: 88, note: 'Estruturado, avaliado' },
      { name: 'RAG', level: 82, note: 'Embeddings, retrieval' },
      { name: 'AI-assisted Dev', level: 90, note: 'Workflow nativo' },
    ],
  },
  {
    id: 'cloud',
    label: 'Cloud / DevOps',
    radarLabel: 'Cloud',
    icon: '◕',
    accent: '#fbbf24',
    accentSoft: 'rgba(251, 191, 36, 0.18)',
    score: 78,
    summary: 'Infra leve, deploy contínuo e observabilidade básica.',
    skills: [
      { name: 'Docker', level: 78, note: 'Multi-stage, compose' },
      { name: 'CI/CD', level: 80, note: 'GitHub Actions' },
      { name: 'Azure', level: 78, note: 'Blob, ADF, Functions' },
      { name: 'Vercel / Edge', level: 85, note: 'Deploy contínuo' },
      { name: 'Observabilidade', level: 72, note: 'Logs, metrics, traces' },
    ],
  },
];
